Adding lots of new integration testing
LabVIEW-DCAF/IntegrationTesting pull request #20
Opened 2017-10-03 20:18 UTC by theSloopJohnB

fix #7 Adding engine status logging
fix #5 adding utilization tests and reporting features.
fix #18 adding timeouts to pipeline
generally clean up reporting code, separating into different files.
added in 9030 target - still need to use new code

2017-10-03 23:00 UTC, DCAF-Builder commented
Bleep bloop!

LabVIEW Diff Robot here with some diffs served up hot for your pull request.

Notice something funny? Help fix me on [my GitHub repo.](https://github.com/LabVIEW-DCAF/buildsystem)


### analyze cpu.vi.png: ![capture](https://raw.githubusercontent.com/DCAF-Builder/diff-pics/master/LabVIEW-DCAF/IntegrationTesting/PR-20/2017-10-03/18%3A00%3A11/analyze%20cpu.vi.png)

### analyze memory usage.vi.png: ![capture](https://raw.githubusercontent.com/DCAF-Builder/diff-pics/master/LabVIEW-DCAF/IntegrationTesting/PR-20/2017-10-03/18%3A00%3A11/analyze%20memory%20usage.vi.png)

### check engine status.vi.png: ![capture](https://raw.githubusercontent.com/DCAF-Builder/diff-pics/master/LabVIEW-DCAF/IntegrationTesting/PR-20/2017-10-03/18%3A00%3A11/check%20engine%20status.vi.png)

### Execute PC Benchmarking.vi.png: ![capture](https://raw.githubusercontent.com/DCAF-Builder/diff-pics/master/LabVIEW-DCAF/IntegrationTesting/PR-20/2017-10-03/18%3A00%3A11/Execute%20PC%20Benchmarking.vi.png)

### Execute-RT-Benchmarking.vi.png: ![capture](https://raw.githubusercontent.com/DCAF-Builder/diff-pics/master/LabVIEW-DCAF/IntegrationTesting/PR-20/2017-10-03/18%3A00%3A11/Execute-RT-Benchmarking.vi.png)

### Invoke RT VI.vi.png: ![capture](https://raw.githubusercontent.com/DCAF-Builder/diff-pics/master/LabVIEW-DCAF/IntegrationTesting/PR-20/2017-10-03/18%3A00%3A11/Invoke%20RT%20VI.vi.png)

### PC Benchmarking.vi.png: ![capture](https://raw.githubusercontent.com/DCAF-Builder/diff-pics/master/LabVIEW-DCAF/IntegrationTesting/PR-20/2017-10-03/18%3A00%3A11/PC%20Benchmarking.vi.png)

### RT-Includes.vi.png: ![capture](https://raw.githubusercontent.com/DCAF-Builder/diff-pics/master/LabVIEW-DCAF/IntegrationTesting/PR-20/2017-10-03/18%3A00%3A11/RT-Includes.vi.png)

### RT-Main.vi.png: ![capture](https://raw.githubusercontent.com/DCAF-Builder/diff-pics/master/LabVIEW-DCAF/IntegrationTesting/PR-20/2017-10-03/18%3A00%3A11/RT-Main.vi.png)

### Run RT VI in project.vi.png: ![capture](https://raw.githubusercontent.com/DCAF-Builder/diff-pics/master/LabVIEW-DCAF/IntegrationTesting/PR-20/2017-10-03/18%3A00%3A11/Run%20RT%20VI%20in%20project.vi.png)

### Set TDMS logfile.vi.png: ![capture](https://raw.githubusercontent.com/DCAF-Builder/diff-pics/master/LabVIEW-DCAF/IntegrationTesting/PR-20/2017-10-03/18%3A00%3A11/Set%20TDMS%20logfile.vi.png)

### test_check engine status.vi.png: ![capture](https://raw.githubusercontent.com/DCAF-Builder/diff-pics/master/LabVIEW-DCAF/IntegrationTesting/PR-20/2017-10-03/18%3A00%3A11/test_check%20engine%20status.vi.png)

### Utilization Report.vi.png: ![capture](https://raw.githubusercontent.com/DCAF-Builder/diff-pics/master/LabVIEW-DCAF/IntegrationTesting/PR-20/2017-10-03/18%3A00%3A11/Utilization%20Report.vi.png)

2017-10-04 16:00 UTC, DCAF-Builder commented
Bleep bloop!

LabVIEW Diff Robot here with some diffs served up hot for your pull request.

Notice something funny? Help fix me on [my GitHub repo.](https://github.com/LabVIEW-DCAF/buildsystem)


### analyze cpu.vi.png: ![capture](https://raw.githubusercontent.com/DCAF-Builder/diff-pics/master/LabVIEW-DCAF/IntegrationTesting/PR-20/2017-10-04/11%3A00%3A19/analyze%20cpu.vi.png)

### analyze memory usage.vi.png: ![capture](https://raw.githubusercontent.com/DCAF-Builder/diff-pics/master/LabVIEW-DCAF/IntegrationTesting/PR-20/2017-10-04/11%3A00%3A19/analyze%20memory%20usage.vi.png)

### check engine status.vi.png: ![capture](https://raw.githubusercontent.com/DCAF-Builder/diff-pics/master/LabVIEW-DCAF/IntegrationTesting/PR-20/2017-10-04/11%3A00%3A19/check%20engine%20status.vi.png)

### Execute PC Benchmarking.vi.png: ![capture](https://raw.githubusercontent.com/DCAF-Builder/diff-pics/master/LabVIEW-DCAF/IntegrationTesting/PR-20/2017-10-04/11%3A00%3A19/Execute%20PC%20Benchmarking.vi.png)

### Execute-RT-Benchmarking.vi.png: ![capture](https://raw.githubusercontent.com/DCAF-Builder/diff-pics/master/LabVIEW-DCAF/IntegrationTesting/PR-20/2017-10-04/11%3A00%3A19/Execute-RT-Benchmarking.vi.png)

### Invoke RT VI.vi.png: ![capture](https://raw.githubusercontent.com/DCAF-Builder/diff-pics/master/LabVIEW-DCAF/IntegrationTesting/PR-20/2017-10-04/11%3A00%3A19/Invoke%20RT%20VI.vi.png)

### PC Benchmarking.vi.png: ![capture](https://raw.githubusercontent.com/DCAF-Builder/diff-pics/master/LabVIEW-DCAF/IntegrationTesting/PR-20/2017-10-04/11%3A00%3A19/PC%20Benchmarking.vi.png)

### RT-Includes.vi.png: ![capture](https://raw.githubusercontent.com/DCAF-Builder/diff-pics/master/LabVIEW-DCAF/IntegrationTesting/PR-20/2017-10-04/11%3A00%3A19/RT-Includes.vi.png)

### RT-Main.vi.png: ![capture](https://raw.githubusercontent.com/DCAF-Builder/diff-pics/master/LabVIEW-DCAF/IntegrationTesting/PR-20/2017-10-04/11%3A00%3A19/RT-Main.vi.png)

### Run RT VI in project.vi.png: ![capture](https://raw.githubusercontent.com/DCAF-Builder/diff-pics/master/LabVIEW-DCAF/IntegrationTesting/PR-20/2017-10-04/11%3A00%3A19/Run%20RT%20VI%20in%20project.vi.png)

### Set TDMS logfile.vi.png: ![capture](https://raw.githubusercontent.com/DCAF-Builder/diff-pics/master/LabVIEW-DCAF/IntegrationTesting/PR-20/2017-10-04/11%3A00%3A19/Set%20TDMS%20logfile.vi.png)

### test_check engine status.vi.png: ![capture](https://raw.githubusercontent.com/DCAF-Builder/diff-pics/master/LabVIEW-DCAF/IntegrationTesting/PR-20/2017-10-04/11%3A00%3A19/test_check%20engine%20status.vi.png)

### Utilization Report.vi.png: ![capture](https://raw.githubusercontent.com/DCAF-Builder/diff-pics/master/LabVIEW-DCAF/IntegrationTesting/PR-20/2017-10-04/11%3A00%3A19/Utilization%20Report.vi.png)

2017-10-06 14:01 UTC, dbendele approved these changes
overall: excited about improved testing and reporting

consider:
make subVI for Read TDMS Log Channel
make subVI for Measure Statistics that calculates standard deviation and arbitrary number of percentile levels
in report subVI set precision to 4 significant digits to improve readability %_4f

question: with this commit did you mean to include Set TDMS logfile.vi

2017-10-06 14:07 UTC, dbendele requested changes
in two analysis VIs you set 'p' input to 99, but label one output as 1st percentile and other 99th percentile

2017-10-06 21:43 UTC, theSloopJohnB commented
Updates:

>make subVI for Read TDMS Log Channel

✔️

>make subVI for Measure Statistics that calculates standard deviation and arbitrary number of percentile levels

✔️

>in report subVI set precision to 4 significant digits to improve readability %_4f

✔️

>question: with this commit did you mean to include Set TDMS logfile.vi

Nope - removed ✔️

>two analysis VIs you set 'p' input to 99, but label one output as 1st percentile and other 99th percentile

✔️

2017-10-06 21:50 UTC, DCAF-Builder commented
Bleep bloop!

LabVIEW Diff Robot here with some diffs served up hot for your pull request.

Notice something funny? Help fix me on [my GitHub repo.](https://github.com/LabVIEW-DCAF/buildsystem)


### analyze cpu.vi.png: ![capture](https://raw.githubusercontent.com/DCAF-Builder/diff-pics/master/LabVIEW-DCAF/IntegrationTesting/PR-20/2017-10-06/16%3A50%3A06/analyze%20cpu.vi.png)

### analyze memory usage.vi.png: ![capture](https://raw.githubusercontent.com/DCAF-Builder/diff-pics/master/LabVIEW-DCAF/IntegrationTesting/PR-20/2017-10-06/16%3A50%3A06/analyze%20memory%20usage.vi.png)

### check engine status.vi.png: ![capture](https://raw.githubusercontent.com/DCAF-Builder/diff-pics/master/LabVIEW-DCAF/IntegrationTesting/PR-20/2017-10-06/16%3A50%3A06/check%20engine%20status.vi.png)

### Execute PC Benchmarking.vi.png: ![capture](https://raw.githubusercontent.com/DCAF-Builder/diff-pics/master/LabVIEW-DCAF/IntegrationTesting/PR-20/2017-10-06/16%3A50%3A06/Execute%20PC%20Benchmarking.vi.png)

### Execute-RT-Benchmarking.vi.png: ![capture](https://raw.githubusercontent.com/DCAF-Builder/diff-pics/master/LabVIEW-DCAF/IntegrationTesting/PR-20/2017-10-06/16%3A50%3A06/Execute-RT-Benchmarking.vi.png)

### Invoke RT VI.vi.png: ![capture](https://raw.githubusercontent.com/DCAF-Builder/diff-pics/master/LabVIEW-DCAF/IntegrationTesting/PR-20/2017-10-06/16%3A50%3A06/Invoke%20RT%20VI.vi.png)

### PC Benchmarking.vi.png: ![capture](https://raw.githubusercontent.com/DCAF-Builder/diff-pics/master/LabVIEW-DCAF/IntegrationTesting/PR-20/2017-10-06/16%3A50%3A06/PC%20Benchmarking.vi.png)

### Read TDMS Double.vi.png: ![capture](https://raw.githubusercontent.com/DCAF-Builder/diff-pics/master/LabVIEW-DCAF/IntegrationTesting/PR-20/2017-10-06/16%3A50%3A06/Read%20TDMS%20Double.vi.png)

### RT-Includes.vi.png: ![capture](https://raw.githubusercontent.com/DCAF-Builder/diff-pics/master/LabVIEW-DCAF/IntegrationTesting/PR-20/2017-10-06/16%3A50%3A06/RT-Includes.vi.png)

### RT-Main.vi.png: ![capture](https://raw.githubusercontent.com/DCAF-Builder/diff-pics/master/LabVIEW-DCAF/IntegrationTesting/PR-20/2017-10-06/16%3A50%3A06/RT-Main.vi.png)

### Run RT VI in project.vi.png: ![capture](https://raw.githubusercontent.com/DCAF-Builder/diff-pics/master/LabVIEW-DCAF/IntegrationTesting/PR-20/2017-10-06/16%3A50%3A06/Run%20RT%20VI%20in%20project.vi.png)

### run stats.vi.png: ![capture](https://raw.githubusercontent.com/DCAF-Builder/diff-pics/master/LabVIEW-DCAF/IntegrationTesting/PR-20/2017-10-06/16%3A50%3A06/run%20stats.vi.png)

### test_check engine status.vi.png: ![capture](https://raw.githubusercontent.com/DCAF-Builder/diff-pics/master/LabVIEW-DCAF/IntegrationTesting/PR-20/2017-10-06/16%3A50%3A06/test_check%20engine%20status.vi.png)

### Timing Report.vi.png: ![capture](https://raw.githubusercontent.com/DCAF-Builder/diff-pics/master/LabVIEW-DCAF/IntegrationTesting/PR-20/2017-10-06/16%3A50%3A06/Timing%20Report.vi.png)

### Utilization Report.vi.png: ![capture](https://raw.githubusercontent.com/DCAF-Builder/diff-pics/master/LabVIEW-DCAF/IntegrationTesting/PR-20/2017-10-06/16%3A50%3A06/Utilization%20Report.vi.png)

2017-10-06 22:42 UTC, dbendele approved these changes

2017-10-06 22:43 UTC, merged